name: mutual_fund_dbt
version: 1.0.0
config-version: 2

profile: mutual_fund_dbt

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  mutual_fund_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

