-- 01_roles_warehouses_databases.sql
-- Creates roles, warehouse, database, schemas, and grants for the portfolio lab.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS AADDATA_PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS AADDATA_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS AADDATA_ANALYST;

GRANT ROLE AADDATA_DATA_ENGINEER TO ROLE AADDATA_PLATFORM_ADMIN;
GRANT ROLE AADDATA_ANALYST TO ROLE AADDATA_PLATFORM_ADMIN;

-- Replace <your_user_name> before running.
-- GRANT ROLE AADDATA_PLATFORM_ADMIN TO USER <your_user_name>;
-- GRANT ROLE AADDATA_DATA_ENGINEER TO USER <your_user_name>;
-- GRANT ROLE AADDATA_ANALYST TO USER <your_user_name>;

CREATE WAREHOUSE IF NOT EXISTS WH_AADDATA_DEV
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Development warehouse for AADData mutual fund Snowflake lab';

GRANT USAGE, OPERATE ON WAREHOUSE WH_AADDATA_DEV TO ROLE AADDATA_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_AADDATA_DEV TO ROLE AADDATA_ANALYST;

CREATE DATABASE IF NOT EXISTS MF_TRANS_DEV
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'Mutual fund transaction platform for SnowPro Core practice';

GRANT OWNERSHIP ON DATABASE MF_TRANS_DEV TO ROLE AADDATA_PLATFORM_ADMIN COPY CURRENT GRANTS;

USE ROLE AADDATA_PLATFORM_ADMIN;
USE WAREHOUSE WH_AADDATA_DEV;
USE DATABASE MF_TRANS_DEV;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Raw source-aligned landing tables';
CREATE SCHEMA IF NOT EXISTS CURATED COMMENT = 'Conformed and validated data';
CREATE SCHEMA IF NOT EXISTS MART COMMENT = 'Dimensional and reporting tables';
CREATE SCHEMA IF NOT EXISTS CONTROL COMMENT = 'Audit, metadata, and pipeline controls';

GRANT USAGE ON DATABASE MF_TRANS_DEV TO ROLE AADDATA_DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MF_TRANS_DEV TO ROLE AADDATA_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE TASK ON SCHEMA RAW TO ROLE AADDATA_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK ON SCHEMA CURATED TO ROLE AADDATA_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK ON SCHEMA MART TO ROLE AADDATA_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CONTROL TO ROLE AADDATA_DATA_ENGINEER;

GRANT USAGE ON DATABASE MF_TRANS_DEV TO ROLE AADDATA_ANALYST;
GRANT USAGE ON SCHEMA MF_TRANS_DEV.MART TO ROLE AADDATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MF_TRANS_DEV.MART TO ROLE AADDATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MF_TRANS_DEV.MART TO ROLE AADDATA_ANALYST;

