-- 06_streams_tasks.sql
-- Practice Snowflake streams and tasks for incremental processing.

USE ROLE AADDATA_PLATFORM_ADMIN;
USE WAREHOUSE WH_AADDATA_DEV;
USE DATABASE MF_TRANS_DEV;

CREATE STREAM IF NOT EXISTS RAW.TRANSACTION_STREAM
  ON TABLE RAW.TRANSACTION
  APPEND_ONLY = TRUE
  COMMENT = 'Captures newly loaded raw transactions';

CREATE TABLE IF NOT EXISTS CONTROL.TRANSACTION_STREAM_AUDIT (
  audit_ts TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  inserted_rows NUMBER
);

CREATE OR REPLACE TASK CONTROL.TASK_AUDIT_TRANSACTION_STREAM
  WAREHOUSE = WH_AADDATA_DEV
  SCHEDULE = 'USING CRON 0 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('RAW.TRANSACTION_STREAM')
AS
INSERT INTO CONTROL.TRANSACTION_STREAM_AUDIT (inserted_rows)
SELECT COUNT(*)
FROM RAW.TRANSACTION_STREAM
WHERE METADATA$ACTION = 'INSERT';

-- Start only when ready.
-- ALTER TASK CONTROL.TASK_AUDIT_TRANSACTION_STREAM RESUME;

SHOW STREAMS IN SCHEMA RAW;
SHOW TASKS IN SCHEMA CONTROL;

-- SnowPro notes:
-- Streams track table change data.
-- Tasks schedule SQL execution.
-- Serverless tasks are also available, but warehouse tasks are easier for first practice.

