-- 08_security_governance.sql
-- Security, governance, and monitoring examples.

USE ROLE AADDATA_PLATFORM_ADMIN;
USE WAREHOUSE WH_AADDATA_DEV;
USE DATABASE MF_TRANS_DEV;

CREATE OR REPLACE TAG CONTROL.DATA_CLASSIFICATION
  ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'PII';

ALTER TABLE CURATED.INVESTOR
  MODIFY COLUMN first_name SET TAG CONTROL.DATA_CLASSIFICATION = 'PII';

ALTER TABLE CURATED.INVESTOR
  MODIFY COLUMN last_name SET TAG CONTROL.DATA_CLASSIFICATION = 'PII';

CREATE OR REPLACE MASKING POLICY CONTROL.MASK_INVESTOR_NAME AS (val STRING)
  RETURNS STRING ->
    CASE
      WHEN CURRENT_ROLE() IN ('AADDATA_PLATFORM_ADMIN', 'AADDATA_DATA_ENGINEER') THEN val
      ELSE '***MASKED***'
    END;

-- Apply after confirming policy behavior in a dev account.
-- ALTER TABLE CURATED.INVESTOR MODIFY COLUMN first_name SET MASKING POLICY CONTROL.MASK_INVESTOR_NAME;
-- ALTER TABLE CURATED.INVESTOR MODIFY COLUMN last_name SET MASKING POLICY CONTROL.MASK_INVESTOR_NAME;

CREATE OR REPLACE SECURE VIEW MART.VW_INVESTOR_HOLDING_SUMMARY AS
SELECT
  h.valuation_date,
  i.investor_id,
  i.investor_type,
  i.country_code,
  h.fund_id,
  h.market_value,
  h.currency_code
FROM MART.FACT_INVESTOR_HOLDING_DAILY h
JOIN MART.DIM_INVESTOR i
  ON h.investor_id = i.investor_id;

GRANT SELECT ON VIEW MART.VW_INVESTOR_HOLDING_SUMMARY TO ROLE AADDATA_ANALYST;

-- Monitoring examples.
SELECT *
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
  DATEADD('hour', -24, CURRENT_TIMESTAMP()),
  CURRENT_TIMESTAMP()
))
ORDER BY start_time DESC
LIMIT 50;

SHOW GRANTS TO ROLE AADDATA_ANALYST;

